// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileUpload(arg1, arg2) {
  return window['go']['main']['App']['FileUpload'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectTorrentFile() {
  return window['go']['main']['App']['SelectTorrentFile']();
}
